version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - docker.env
    volumes:
      - .:/app
      - db_data:/var/lib/postgresql/data
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
