# Generated by Django 4.2.4 on 2024-08-29 11:13

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 9, 5, 11, 13, 0, 425386, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="date expired",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date published"
            ),
        ),
    ]
