# Generated by Django 4.2.4 on 2024-08-29 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_question_end_date_alter_question_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 9, 5, 11, 28, 31, 19823, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="date expired",
            ),
        ),
    ]
