# Generated by Django 4.2.4 on 2024-08-31 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_question_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 9, 7, 7, 22, 9, 206174, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="date expired",
            ),
        ),
    ]
